### ISSUE TITLE
footer shoudln't be sticky

### ISSUE THREAD

**Issue by kevicebryan** [akhileshverma92/campusfest#3]
i think that the footer being sticky might be a problem, as can be seen here it is covering the submit registration compoenent, 
I'd love to be assigned to fix this and also revampe the footer 🙏

![image](https://github.com/user-attachments/assets/c25dd02d-1442-43b3-8f30-19817408cfcd)

**Comment by JaiSharma1710** [comment]
HI @akhileshverma92 i have fixed this issue please look into this and let me know if any thing else is needed
