### ISSUE TITLE
Improving the overall UI of the Register section

### ISSUE THREAD

**Issue by Bhavishya2601** [akhileshverma92/campusfest#56]
The register is very basic, looks like it's made from chatGPT , but we can change
What i wanna do is cut off the register section from there and make a new page for it, and then we can add great styling on it as it is in different page 

Please assign this issue to me under hactoberfest

**Comment by akhileshverma92** [comment]
show me some ui template 
@Bhavishya2601

**Comment by Bhavishya2601** [comment]
@akhileshverma92 there are many designs
I can show you some like
![Screenshot 2024-10-09 091011](https://github.com/user-attachments/assets/0a14be6c-6a97-47a0-9278-43bd06050c1b)
we can just change according to your theme, the text fields can be little transparent

in the background, instead of a photo, we could have a video of a campus or the same one on the homepage playing in slightly blur and have the fields on top of it


if you have anything else in mind, you can tell me that as well

**Comment by Bhavishya2601** [comment]
@akhileshverma92  which one should i go for

if you have something in mind, you can tell me
